spring:
  application:
    name: scorch
  profiles:
    active: local
---
server:
  port: 8787
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
spring:
  profiles: local
  jackson:
    serialization:
      indent_output: true
  data:
    rest:
      basePath: "/v1/repositories"
  cloud:
    zookeeper:
      connect-string: "192.168.59.103:2181"
      dependencies:
        scorch:
          path: "/scorch"
          loadBalancerType: ROUND_ROBIN
          contentTypeTemplate: "application/json"
          version: v1
  rabbitmq:
    addresses: "amqp://192.168.59.103:5672"
---
server:
  port: 8787
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
spring:
  profiles: docker
  jackson:
    serialization:
      indent_output: true
  data:
    rest:
      basePath: "/v1/repositories"
  cloud:
    zookeeper:
      connect-string: "zookeeper:2181"
      dependencies:
        scorch:
          path: "/scorch"
          loadBalancerType: ROUND_ROBIN
          contentTypeTemplate: "application/json"
          version: v1
  rabbitmq:
    addresses: "amqp://rabbit:5672"